#loggin from mainze github
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#end of logging
spring:
  main:
    banner-mode: OFF
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: 2241323m
